repos:
      - repo: https://github.com/PyCQA/flake8
        rev: 3.8.3
        hooks:
              - id: flake8
                files: filigree/.*\.py$

default_language_version:
      python: python3
